# fly.toml app configuration file generated for free-tribe-network-wp on 2025-06-16T15:30:43+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'free-tribe-network-wp'
primary_region = 'lhr'

[build]
  dockerfile = "Dockerfile"

[env]
  WORDPRESS_DB_HOST = "freetribenetwork-wordpress-db.internal"
  WORDPRESS_DB_NAME = "some_db"
  WORDPRESS_DB_USER = "non_root_user"
  # Set WORDPRESS_DB_PASSWORD with `fly secrets set`

[mounts]
  source="wp_content"
  destination="/var/www/html/wp-content"

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
